services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
    volumes:
      - "./localstack:/temp/localstack"  # Optional: persist data

  etl-pipeline:
    build: .
    depends_on:
      - localstack
    volumes:
      - .:/app
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    command: python etl_pipeline.py
